###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing import Dict, List, Optional, Union


class InputDataType(str, Enum):
    
    TEXT = "TEXT"
    NUMBER = "NUMBER"

class Attribute(BaseModel):
    
    
    name: str
    value: str

class Element(BaseModel):
    
    
    tagName: str
    attributes: List["Attribute"]
    textContent: str
    outerHTML: str

class ResponseFormat(BaseModel):
    
    
    elementIdentifier: str
    code: str
